// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v55 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v55));
        
        string IMigrationMetadata.Id
        {
            get { return "201212282136515_v5.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
