// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1));
        
        string IMigrationMetadata.Id
        {
            get { return "201212150728202_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
