// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v56 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v56));
        
        string IMigrationMetadata.Id
        {
            get { return "201212282152208_v5.6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
