// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v60 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v60));
        
        string IMigrationMetadata.Id
        {
            get { return "201301032142096_v6.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
