// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v61));
        
        string IMigrationMetadata.Id
        {
            get { return "201301032221233_v6.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
