// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _57 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_57));
        
        string IMigrationMetadata.Id
        {
            get { return "201301010731188_5.7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
