// <auto-generated />
namespace ToolDepot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v59 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v59));
        
        string IMigrationMetadata.Id
        {
            get { return "201301021625350_v5.9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
